version: '3'

services:

  app:
    image: example-project2-app
    build:
      context: ./app
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./app:/opt/app
    depends_on:
      - db

  db:
    image: postgres:10.0
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "app"
